board/urls.py
from django.contrib import admin
from django.urls import path, include

##import ...은 아래 주석친 문장들을 보이지 않게 만들어놓은것임
##from django.contrib import admin
##from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noticeboard/', include('noticeboard.urls')),
]

noticeboard/urls.py
from django.urls import path
from . import views #.은 현재 즉 노티스 파일을 말함

app_name = 'noticeboard'
urlpatterns = [
    path('',views.index, name='index'), #views 파일의 index라는 함수를 호출하고 이걸 index이라는 주소이름을 준다.
    #그래서 noticeboard로 들어오면 무조건 저 url을 거치는데 거기서 함수가 나오므로 함수를 통해 주소를 줄수 있는것이다.
    path('write/', views.write_article, name='write_article'),
    path('add/', views.add_article, name='add_article'),
    path('<int:article_id>/', views.view_article, name='view'),
    path('update/<int:article_id>/', views.update_article, name='update'),
    path('delete/<int:article_id>', views.delete_article, name='delete'),
]

noticeboard/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    writeDate = models.DateTimeField(default=now, editable=False)
    writeID = models.CharField(max_length=50)

    def __str__(self):
        return self.title

noticeboard/views.py
from django.shortcuts import render, get_object_or_404
from noticeboard.models import Notice
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
# Create your views here.

def index(request):
    article_list = Notice.objects.all().order_by('-writeDate')
    #이렇게 하면 notice오브젝트안에 있는 모든것을 다 가져온다. orderby 하는데 '-'desc로 writeDate라는 컬럼을 기준으로 정렬
    context = {'article_list':article_list}
    return render(request, 'noticeboard/index.html', context)
##request를 받으면 noticeboard/index.html과 context를 뿌려준다.(context는 딕셔너리 형태로 넘겨준다.)


def write_article(request):
    return render(request, 'noticeboard/writeArticle.html')


def add_article(request):
    notice = Notice()
    notice.title = request.POST['title']
    notice.content = request.POST['content']
    notice.writeID = 'root' #아직 안만들었기 때문에 임의로 넣음
    notice.save()  #장고에서 제공하는 저장 기능
    return HttpResponseRedirect(reverse('noticeboard:index'))
#redirect는 클라이언트에게 정보를 보내는게 아니라 클라이언트가 스스로 이미 받은 정보를 호출하도록 지시하는것으로 볼수 있고
#이때 지시를 하면서 주소를 같이 보내줘야 한다. 이러한 지시를 내리기 위해 필요한것이 reverse이다. 계속
# 쓰고있는 장고의 url language와 같은 기능을
#하는것으로 볼수 있다.(소스를 안바꾸면서도 다른 기능을 하도록한다.)

def view_article(request, article_id):
    notice = get_object_or_404(Notice, pk=article_id) #Notice 에서 article_id가 pk이인 놈들을 불러오는데
    #없으면 get object or 404를 이용해서 NOT FOUND를 출력해주는 것이다.
    return render(request, 'noticeboard/detail.html', {'article':notice})  #넘겨줄떄는 딕셔너리 형태로 넘겨줘야 한다.
#딕셔너리 부분이 사용자로부터 받은 부분임



def update_article(request, article_id):
    notice = Notice.objects.get(id=article_id)
    #get_object_or_404을 쓰지 않은것은 당연히 있는놈을 받아온것이기떄문에 없을리가 없기 떄문이다.
    if request.method == 'POST':
        #주소창에 수동타이핑으로 입력해서 들어온경우를 방지하기 위함
        notice.writeID = request.POST['writer']
        notice.title = request.POST['title']
        #'title'은 name attribite의 값을 말함
        notice.content = request.POST['content']
        notice.writeDate = timezone.datetime.now()
        notice.save()
        return HttpResponseRedirect(reverse('noticeboard:view', args=(article_id,)))
        #파이썬 튜플에서 원소가 하나인경우에는 반드시 콤마를 붙여줘야 튜플로 인식이된다.
    else:
        return render(request, 'noticeboard/detail.html', {'article':notice})



def delete_article(request, article_id):
    notice = Notice.objects.get(id=article_id)
    notice.delete()
    return HttpResponseRedirect(reverse('noticeboard:index'))

templates/noticeboard/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>글보기</title>
    <style>
        #tr_btn_modify {
            display: none;
        }
    </style>
    <script>
        function backToList(obj) {
            obj.action = "{% url 'noticeboard:index' %}";
            obj.submit();
        }

        function fn_enable(obj) {
            document.querySelector('#i_writer').disabled = false;
            document.querySelector('#i_title').disabled = false;
            document.querySelector('#i_content').disabled = false;
            document.querySelector('#tr_btn_modify').style.display="block";
            document.querySelector('#tr_btn').style.display="none";
        }

        function fn_modify_article(obj) {
            obj.action = "{% url 'noticeboard:update' article.id %}";
            obj.submit();
        }

        function fn_remove_article(obj) {
            obj.action = "{% url 'noticeboard:delete' article.id %}";
            obj.submit();
        }

    </script>


</head>
<body>
    <form name="frmArticle" method="POST">
        {% csrf_token %}
        <table border="0" align="center">
            <tbody>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">글번호</td>
                    <td><input type="text" value="{{article.id}}" disabled/></td>
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">작성자ID</td>
                    <td><input type="text" value="{{article.writeID}}" name="writer" id="i_writer" disabled/></td>
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">제목</td>
                    <td><input type="text" value="{{article.title}}" name="title" id="i_title" disabled/></td>
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">내용</td>
                    <td><textarea rows="20" cols="60" name="content" id="i_content" disabled>{{article.content}}</textarea></td>
                </tr>
                <tr>
                    <td width="20%" align="center" bgcolor="#FF9933">등록일자</td>
                    <td><input type="text" value="{{article.writeDate}}" disabled/></td>
                </tr>
                <tr id="tr_btn_modify">
                    <td colspan="2" align="center">
                        <input type="button" value="수정반영하기" onclick="fn_modify_article(frmArticle)">
                        <input type="button" value="취소" onclick="backToList(frmArticle)">
                    </td>
                </tr>
                <tr id="tr_btn">
                    <td colspan="2" align="center">
                        <input type="button" value="수정하기" onclick="fn_enable(frmArticle)">
                        <input type="button" value="삭제하기" onclick="fn_remove_article(frmArticle)">
                        <input type="button" value="리스트로 돌아가기" onclick="backToList(frmArticle)">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</body>
</html>

templates/noticeboard/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>게시글목록</title>
    <style>
        .cls1 {
        color : gray;
        text-decoration: none;
        }
        .cls2 {
        text-align: center;
        font-size: 30px;
        display: block;
        }

        #menubar {
	    background : red;
        }
        #menubar ul {
	    margin : 0;
	    padding : 0;
	    width : 567px;
        }
        #menubar ul li {
	    display : inline-block;
	    list-style-type : none;
	    padding : 0px 15px; /* top=bottom=0, left=right=15px */
        }
        #menubar ul li a {
	    color : white;
  	    text-decoration : none;
        }
        #menubar ul li a:hover {
 	    color : violet;
        }

        table tfoot{
            color:red;
            background : black;
        }

        #firstb tr{
            background : blue;
            color : white;
        }




    </style>
</head>
<body>

    <nav id="menubar">
	<ul>
		<li><a href="#">메뉴</a></li>
		<li><a href="#">연혁</a></li>
		<li><a href="#">직원</a></li>
		<li><a href="#">공지사항</a></li>
		<li><a href="#">게시판</a></li>
	</ul>
    </nav>











    <table frame ="void" cellspacing="0" align="center" border="1" width="80%">
        <thead>
            <tr height="10" align="center" bgcolor="white">
                <th>글번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>
        <tfoot>
            <tr height="10" align="center" >
                <th colspan="4" >빨갱이를 죽이자!</th>
            </tr>
        </tfoot>

        {% if article_list %}
        <tbody id="firstb">
            {% for article in article_list%}
            <tr align="center">
                <td width="5%">{{forloop.counter}} <!--중괄호를 두번씩 쓰면 변수로 알아듣는다.--></td>
                <td width="10%">{{article.writeID}}</td>
                <td align="left" width="35%">
                    <span style="padding-right:30px"></span>
                    <a class="cls1" href="{% url 'noticeboard:view' article.id %}">{{article.title}}</a>
                </td>
                <td width="10%">{{article.writeDate}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <tbody>
            <tr height="10">
                <td colspan="4">
                    <p align="center">
                        <b><span style="font-size:15pt;">등록된 글이 없습니다.</span></b>
                    </p>
                </td>
            </tr>
        </tbody>


        {% endif %}





    </table>
    <a class="cls1" href="{% url 'noticeboard:write_article' %}">
        <span class="cls2">글싸지르기</span>
    </a>

</body>
</html>

templates/noticeboard/writeArticle.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>새글 쓰기</title>
    <script>
        function backToList(obj) {
            obj.action="{% url 'noticeboard:index' %}";
            obj.submit();
        }
    </script>
</head>
<body>
    <h1 style="text-align:center">새글 쓰기</h1>
    <form name="articleForm" method="post" action="{% url 'noticeboard:add_article' %}">
        {% csrf_token %}
            <table boder="0" align="center">
                <tbody>
                    <tr>
                        <td align="right">글제목</td>
                        <td colspan="2"><input type="text" size="71" maxlength="100" name="title" /></td>
                    </tr>
                    <tr>
                        <td align="right" valign="top"><br>글내용:</td>
                        <td colspan="2"><textarea name="content" rows="10" cols="65" maxlength="2000">
                        </textarea></td>
                    </tr>
                    <tr>
                        <td align="right"></td>
                        <td colspan="2"><input type="submit" value="글쓰기"/>
                        <input type="button" value="목록보기" onclick="backToList(this.form)"/></td>
                    </tr>
                </tbody>
            </table>
    </form>
</body>
</html>